apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: my-wordpress
  namespace: wordpress
spec:
  releaseName: my-wordpress
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: wordpress
  interval: 50m
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx